// Build script — run with `node build.js` (Cloudflare runs it automatically on every deploy).
// 1. Turns narrative-en.md / narrative-de.md / narrative-fr.md into knowledge.js (the assistant's knowledge per language).
// 2. Wraps index.html into a complete page at public/index.html and copies photo.jpg / photo-2.jpg next to it.

const fs = require("fs");
const path = require("path");

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");
const write = (p, s) => { fs.mkdirSync(path.dirname(path.join(root, p)), { recursive: true }); fs.writeFileSync(path.join(root, p), s); };

// ---- 1. knowledge (one document per language; DE/FR fall back to EN if the file is missing) ----
function loadNarrative(lang) {
  const file = `narrative-${lang}.md`;
  if (!fs.existsSync(path.join(root, file))) return null;
  let t = read(file);
  t = t.replace(/^\*[^\n]*\*\n/m, "");                                   // editorial note at the top
  t = t.replace(/\n\*Alternativ[^\n]*\n\n?(?:- [^\n]*\n)+/g, "\n");        // one-liner alternatives (for review only)
  t = t.replace(/\n## (Website-Texte|Textes du site)[\s\S]*$/, "\n");     // UI text lists (for review only)
  return t;
}
const KN = { en: loadNarrative("en") };
KN.de = loadNarrative("de") || KN.en;
KN.fr = loadNarrative("fr") || KN.en;
write("knowledge.js", `// GENERATED by build.js from narrative-*.md — do not edit by hand.\nexport const KNOWLEDGE = ${JSON.stringify(KN)};\n`);

// ---- 2. page ----
const src = read("index.html");
const head = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="index,follow">
<meta property="og:title" content="Christian Constant">
<meta property="og:description" content="You have made it here. That makes you special already. Executive coaching in Zurich, by referral.">
<meta property="og:type" content="website">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='16' fill='%231D4F6E'/%3E%3Ctext x='16' y='21' text-anchor='middle' font-family='Georgia,serif' font-size='15' fill='white'%3Ecc%3C/text%3E%3C/svg%3E">
`;
const live = src.replace("__DEMO__", "false");
const split = live.indexOf("<header");            // everything before <header> is head content (title, fonts, styles)
write("public/index.html", head + live.slice(0, split) + "</head>\n<body>\n" + live.slice(split) + "\n</body>\n</html>\n");
fs.copyFileSync(path.join(root, "photo.jpg"), path.join(root, "public/photo.jpg"));
if (fs.existsSync(path.join(root, "photo-2.jpg"))) fs.copyFileSync(path.join(root, "photo-2.jpg"), path.join(root, "public/photo-2.jpg"));

// Preview copy for the Claude artifact (demo answers on, photo inlined). Not used by the deployed site.
const photoUri = "data:image/jpeg;base64," + fs.readFileSync(path.join(root, "photo.jpg")).toString("base64");
const photo2Uri = fs.existsSync(path.join(root, "photo-2.jpg")) ? "data:image/jpeg;base64," + fs.readFileSync(path.join(root, "photo-2.jpg")).toString("base64") : "photo-2.jpg";
write("preview/index.html", src.replace("__DEMO__", "true").replace('src="photo.jpg"', 'src="' + photoUri + '"').replace('src="photo-2.jpg"', 'src="' + photo2Uri + '"'));

console.log("built: knowledge.js (" + Object.keys(KN).join(", ") + "), public/index.html, public/photo.jpg, preview/index.html");
